# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: laiyao.proto
# Protobuf Python Version: 4.25.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0claiyao.proto\"\xe0\x01\n\tAttrValue\x12\x0b\n\x01s\x18\x02 \x01(\x0cH\x00\x12\x0b\n\x01i\x18\x03 \x01(\x03H\x00\x12\x0b\n\x01\x66\x18\x04 \x01(\x02H\x00\x12\x0b\n\x01\x62\x18\x05 \x01(\x08H\x00\x12\x1d\n\x04\x66unc\x18\n \x01(\x0b\x32\r.NameAttrListH\x00\x12\x15\n\x0bplaceholder\x18\t \x01(\tH\x00\x1a`\n\tListValue\x12\t\n\x01s\x18\x02 \x03(\x0c\x12\r\n\x01i\x18\x03 \x03(\x03\x42\x02\x10\x01\x12\r\n\x01\x66\x18\x04 \x03(\x02\x42\x02\x10\x01\x12\r\n\x01\x62\x18\x05 \x03(\x08\x42\x02\x10\x01\x12\x1b\n\x04\x66unc\x18\t \x03(\x0b\x32\r.NameAttrListB\x07\n\x05value\"|\n\x0cNameAttrList\x12\x0c\n\x04name\x18\x01 \x01(\t\x12%\n\x04\x61ttr\x18\x02 \x03(\x0b\x32\x17.NameAttrList.AttrEntry\x1a\x37\n\tAttrEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x19\n\x05value\x18\x02 \x01(\x0b\x32\n.AttrValue:\x02\x38\x01\"\x81\x01\n\x07NodeDef\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05input\x18\x02 \x03(\t\x12 \n\x04\x61ttr\x18\x05 \x03(\x0b\x32\x12.NodeDef.AttrEntry\x1a\x37\n\tAttrEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x19\n\x05value\x18\x02 \x01(\x0b\x32\n.AttrValue:\x02\x38\x01\"\"\n\x08GraphDef\x12\x16\n\x04node\x18\x01 \x03(\x0b\x32\x08.NodeDefb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'laiyao_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_ATTRVALUE_LISTVALUE'].fields_by_name['i']._options = None
  _globals['_ATTRVALUE_LISTVALUE'].fields_by_name['i']._serialized_options = b'\020\001'
  _globals['_ATTRVALUE_LISTVALUE'].fields_by_name['f']._options = None
  _globals['_ATTRVALUE_LISTVALUE'].fields_by_name['f']._serialized_options = b'\020\001'
  _globals['_ATTRVALUE_LISTVALUE'].fields_by_name['b']._options = None
  _globals['_ATTRVALUE_LISTVALUE'].fields_by_name['b']._serialized_options = b'\020\001'
  _globals['_NAMEATTRLIST_ATTRENTRY']._options = None
  _globals['_NAMEATTRLIST_ATTRENTRY']._serialized_options = b'8\001'
  _globals['_NODEDEF_ATTRENTRY']._options = None
  _globals['_NODEDEF_ATTRENTRY']._serialized_options = b'8\001'
  _globals['_ATTRVALUE']._serialized_start=17
  _globals['_ATTRVALUE']._serialized_end=241
  _globals['_ATTRVALUE_LISTVALUE']._serialized_start=136
  _globals['_ATTRVALUE_LISTVALUE']._serialized_end=232
  _globals['_NAMEATTRLIST']._serialized_start=243
  _globals['_NAMEATTRLIST']._serialized_end=367
  _globals['_NAMEATTRLIST_ATTRENTRY']._serialized_start=312
  _globals['_NAMEATTRLIST_ATTRENTRY']._serialized_end=367
  _globals['_NODEDEF']._serialized_start=370
  _globals['_NODEDEF']._serialized_end=499
  _globals['_NODEDEF_ATTRENTRY']._serialized_start=312
  _globals['_NODEDEF_ATTRENTRY']._serialized_end=367
  _globals['_GRAPHDEF']._serialized_start=501
  _globals['_GRAPHDEF']._serialized_end=535
# @@protoc_insertion_point(module_scope)
